[formatting]
align_entries = false
align_comments = false
array_trailing_comma = true
compact_arrays = false
compact_inline_tables = false
column_width = 120
indent_string = "    "
reorder_keys = false